version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "paper"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "change_me"
      RCON_PORT: "25575"
    ports:
      - "25575:25575"
      - "25565:25565"
      - "4567:4567"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
  astro:
    image: node:20
    command: sh -c "npx astro dev --host"
    working_dir: /app
    volumes:
      - ./astro-map:/app
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
volumes:
  data: {}
