version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "paper"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "change_me"
      RCON_PORT: "25575"
    ports:
      - "25575:25575"
      - "25565:25565"
      - "4567:4567"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
  backup:
    image: itzg/mc-backup
    environment:
      RCON_HOST: mc
      BACKUP_METHOD: restic
      RESTIC_PASSWORD: password
      RESTIC_REPOSITORY: rclone:s3:bonkerbourgers
    volumes:
      # mount volume pre-configured using a host mounted file
      - ./rclone.conf:/config/rclone/rclone.conf
      # or configure one into a named volume using
      # docker run -it --rm -v rclone-config:/config/rclone rclone/rclone config
      # and change the above to
      # - rclone-config:/config/rclone
      - ./data:/data:ro
      - backups:/backup
  astro:
    image: node:20
    command: sh -c "npm install && npx astro dev --host"
    working_dir: /app
    volumes:
      - ./astro-map:/app
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
volumes:
  data: {}
  backups: {}
